### ISSUE TITLE
Update AA audit setup workflow for hybrid audit

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1048]
Hybrid version is almost identical to the ballot comparison workflow, so starting from there we need to:
- Replace the Target Contest/Opportunistic Contest screens from the ballot comp workflow with a modified version of the screens from the ballot polling workflow (see screenshot attached). Modifications include:
-- Changing the Contest Name text box at the top of the screen to a dropdown menu, prepopulated with the contest names from the Standardized Contest List, and [Hybrid Target Contest Screen.pdf]
-- Removing the Contest Universe selector at the top of the page, since the contest universes are already defined in the Standardized Contest List.
[Hybrid Target Contest Screen.pdf](https://zube.io/files/votingworks/4990cd6ba0705cf581014952bb78af5b-hybrid-target-contest-screen.pdf)

**Comment by MorganLove** [comment]
@mcchilders a couple questions:

1) the Hybrid Target Contest Screen mockup link is broken :)

2) can I get sample files for Hybrid audits, or let me know which ones are identical to the other types? I'm assuming they'd be similar to the ballot comparison files, but the standardized contest list would be different since it includes the information necessary to define the contest universe, right?

**Comment by mcchilders** [comment]
@Morgan-Love sorry about that link - should work now!

All the audit setup files are the same as ballot comparison. The standardized contest list already includes the jurisdictions that contain that contest ("Jurisdictions" column), which defines the universe for the contest.

**Comment by MorganLove** [comment]
@mcchilders Thanks for the clarification!

I'm still seeing just square brackets around the name of the file, and no attachment, haha.
